server:
  port: 7080

url:
  instagram:
    get-post-ids: https://graph.instagram.com/%s/media?access_token=%s
    get-post-details: https://graph.instagram.com/%s/media?access_token=%s

instagram:
  profile-id: 5022499404471247
  fields: fields,id,caption,media_type,media_url,timestamp
  access-token: IGQVJYWHJ1Y3gxSHFuUWNRbEtzRXNUOWs4NFJTTEJvbXRISExaeFNJY0ZAycmprTm1oeXdadGEzR1ZAaaHFodTIzRE9sMXo5R1BXakNMVGJsUno2eXc4RWFRSjA2Q1dob0RlMk1HdFJmY2s2OHBzX3pwegZDZD

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/neonazerbaijandb
    username: postgres
    password: root
    #    password: 12345
    driverClassName: org.postgresql.Driver