server:
  port: 9090

url:
  instagram:
    get-latest-post-details: https://graph.instagram.com/%s/media?fields=%s&access_token=%s&limit=1
    get-all-posts-details: https://graph.instagram.com/%s/media?fields=%s&access_token=%s&limit=100
  telegram:
    send-photo: https://api.telegram.org/bot%s/sendPhoto
#    get-post-details: https://graph.instagram.com/%s/media?access_token=%s

instagram:
  profile-id: 5362713430462517
  fields: id,media_type,media_url,caption,timestamp
  access-token: IGQVJWNEJZASGs3Q2gtSzRQdEpkWm9VTHBYelh3NWpvTC1DTUpBcWxlLTRHMWJGZAVlHQ3Y5cWhxOVRQNkZAGTFp5Qm1lWEZAlbnJKcTAtdm4tOVNnSWk5R1diNTFja3FBa3ZAONWk3R1ZALS251N2ZAEeUNQZAgZDZD

telegram:
  chat-id: -1001428237886 #-605409547
  token: 5376848163:AAEMtLZJ4xzE4-TUSNJU-vxe56RSOifkvrc

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/neonazerbaijandb
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver